name: PR
# Checks title linting and labeling.

on:
  workflow_call:

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}

  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Labels
        uses: actions/labeler@v6
      - name: Apply Size Label
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files_to_ignore: |
            **/*.md
            **/*.lock
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "100": "M",
              "500": "L",
              "1000": "XL"
            }
