name: Release Please Reusable
# Release automation workflow powered by release-please.

on:
  workflow_call:
    inputs:
      config_file:
        required: false
        type: string
        default: .github/release-please-config.json
      manifest_file:
        required: false
        type: string
        default: .github/.release-please-manifest.json

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ github.token }}
          config-file: ${{ inputs.config_file }}
          manifest-file: ${{ inputs.manifest_file }}
