name: StyLua

on:
  workflow_call:
    inputs:
      version:
        description: StyLua version
        required: false
        type: string
        default: latest
      args:
        description: StyLua CLI args
        required: false
        type: string
        default: --check .

permissions:
  contents: read

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          args: ${{ inputs.args }}
